input_dir: './input'
output_dir: './output'
stage:
  testing:
    name: sim
    input_ftp: ftp://bob/
    fusio: http://bob/cgi-bin/fusio.dll/api?
    navitia: https://test.api.navitia.io
    contributor_id: NAN
    service_id: 3
  production:
    name: prod
    input_ftp: ftp://bobette/
    fusio: http://bobette/cgi-bin/fusio.dll/api?
    navitia: https://api.navitia.io
    contributor_id: NAN
    service_id: 3
