input_dir: './input'
backup_dir: './backup'
coverage: fr-pdl
contributor_id: NAN
stage:
  testing:
    name: sim
    input_ftp: ftp://bob/
    fusio:
       ihm_url: url #add fusio ihm url
       ihm_login: login #add fusio ihm user login
       ihm_password: password #add fusio ihm user password
       dll: url #add fusio dll url
    navitia:
        url: url #add fusio ihm url
        token: token #add navitia token
    service_id: 3
  production:
    name: prod
    input_ftp: ftp://bobette/
    fusio:
       ihm_url: url #add navitia url
       ihm_login: login #add fusio ihm user login
       ihm_password: password #add fusio ihm user password
       dll: url #add fusio dll url
    navitia:
        url: url 
        token: token
    service_id: 3

fusio:
  contributor_id: 5
  service_id: 1


loggers:
  version: 1
  disable_existing_loggers: False
  formatters:
      simple:
          format: "[%(asctime)s] [%(levelname)5s] [%(process)5s] [%(name)25s] %(message)s"
  handlers:
      console:
          class: logging.StreamHandler
          level: DEBUG
          formatter: simple
          stream: ext://sys.stdout
      file_handler:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: simple
          filename: ronal.log
          maxBytes: 10485760 # 10MB
          backupCount: 20
          encoding: utf8
  root:
      level: DEBUG
      handlers: [console, file_handler]
