input_dir: './input'
output_dir: './output'
coverage: fr-pdl
contributor_id: NAN
stage:
  testing:
    name: sim
    input_ftp: ftp://bob/
    fusio: http://bob/cgi-bin/fusio.dll/api?
    navitia:
        url: url #add url navitia
        token: token #add token for navitia
    service_id: 3
  production:
    name: prod
    input_ftp: ftp://bobette/
    fusio: http://bobette/cgi-bin/fusio.dll/api?
    navitia:
        url: url 
        token: token 
    service_id: 3
ihm:
  fusio: http://fusio-ihm.fr-pdl-priv.dev.canaltp.fr/
  action: dataupdate
  contributor_id: 5
  service_id: 1

loggers:
  version: 1
  disable_existing_loggers: False
  formatters:
      simple:
          format: "[%(asctime)s] [%(levelname)5s] [%(process)5s] [%(name)25s] %(message)s"
  handlers:
      console:
          class: logging.StreamHandler
          level: DEBUG
          formatter: simple
          stream: ext://sys.stdout
      file_handler:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: simple
          filename: ronal.log
          maxBytes: 10485760 # 10MB
          backupCount: 20
          encoding: utf8
  root:
      level: DEBUG
      handlers: [console, file_handler]
