input_dir: './input'
output_dir: './output'
coverage: fr-pdl
contributor: NAN
stage:
  testing:
    name: sim
    fusio: ftp://bob
    navitia:
        url: http://vippriv-jormsim-ws.mutu.prod.canaltp.prod
        token: fd5c66c1-2b1d-407d-bd07-dfbb01e6aba7
  production:
    name: prod
    fusio: ftp://bobette
    navitia:
        url: http://vippriv-jorm-ws.mutu.prod.canaltp.prod
        token: 06630be8-8584-402c-8b1c-d70985298652
